"""Structural dependency analysis for PyTorch, independent of pruning policy."""

from .contracts import (
    ArgumentRef,
    AxisBarrier,
    Balanced,
    Barrier,
    BlockBalance,
    Diagnostic,
    Divisible,
    Fixed,
    Impact,
    LayoutConstraint,
    NonEmpty,
    Requirement,
    ShapeExpr,
)
from .errors import (
    AnalysisLimitError,
    CaptureError,
    KirigamiError,
    StaleGraphError,
    UnsupportedOperation,
)
from .graph import CallRef, DependencyGraph
from .operation import (
    CallEffects,
    CandidateAxis,
    OperationContext,
    OperatorRule,
    OperatorSpec,
    OutputContract,
    PartitionedLayout,
    TensorFacts,
)
from .registry import OperatorRegistry
from .relations import (
    AxisPort,
    AxisRelation,
    BlockMap,
    BroadcastRelation,
    PermuteRelation,
    ReshapeRelation,
    SliceRelation,
)
from .selection import AxisRef, IndexSet, Region, Selection, TensorRef

__all__ = [
    "AnalysisLimitError",
    "ArgumentRef",
    "AxisBarrier",
    "AxisPort",
    "AxisRef",
    "AxisRelation",
    "Balanced",
    "Barrier",
    "BlockBalance",
    "BlockMap",
    "BroadcastRelation",
    "CallEffects",
    "CallRef",
    "CandidateAxis",
    "CaptureError",
    "DependencyGraph",
    "Diagnostic",
    "Divisible",
    "Fixed",
    "Impact",
    "IndexSet",
    "KirigamiError",
    "LayoutConstraint",
    "NonEmpty",
    "OperationContext",
    "OperatorRegistry",
    "OperatorRule",
    "OperatorSpec",
    "OutputContract",
    "PartitionedLayout",
    "PermuteRelation",
    "Region",
    "Requirement",
    "ReshapeRelation",
    "Selection",
    "ShapeExpr",
    "SliceRelation",
    "StaleGraphError",
    "TensorFacts",
    "TensorRef",
    "UnsupportedOperation",
]
